# Generated by Django 5.2.1 on 2025-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_level', models.IntegerField()),
                ('continent_code', models.CharField(max_length=10)),
                ('continent_name', models.CharField(max_length=50)),
                ('continent_eng_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('country_eng_name', models.CharField(max_length=50)),
                ('country_iso_code', models.CharField(max_length=10)),
                ('region_type', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('written_date', models.DateField()),
                ('map_url', models.URLField()),
                ('flag_url', models.URLField()),
                ('danger_map_url', models.URLField()),
            ],
        ),
    ]
