# Generated by Django 5.2.1 on 2025-06-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('alarm_level', models.IntegerField()),
                ('continent_name', models.CharField(max_length=100)),
                ('written_dt', models.DateField()),
                ('region_type', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('map_url', models.URLField()),
                ('flag_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='TravelAlert',
        ),
    ]
