# Generated by Django 5.2.1 on 2025-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_id', models.CharField(max_length=30, unique=True)),
                ('country_name', models.CharField(max_length=50)),
                ('country_en_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('written_dt', models.DateField()),
            ],
        ),
    ]
