# Generated by Django 5.2.2 on 2025-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_safetynotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embassy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_en_name', models.CharField(max_length=50)),
                ('embassy_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('tel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_tel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
