# Generated by Django 5.2.2 on 2025-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_embassy'),
    ]

    operations = [
        migrations.AddField(
            model_name='embassy',
            name='embassy_cd',
            field=models.CharField(default='temp_cd', max_length=20, unique=True),
        ),
    ]
