# Generated by Django 5.2.2 on 2025-06-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_embassy_embassy_cd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embassy',
            old_name='emergency_tel_no',
            new_name='urgency_tel',
        ),
    ]
