# Generated by Django 5.2.2 on 2025-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_rename_emergency_tel_no_embassy_urgency_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='embassy',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
