# Generated by Django 5.2.2 on 2025-06-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_embassy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embassy',
            name='urgency_tel',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
