# Generated by Django 5.2.2 on 2025-06-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_alter_embassy_urgency_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbassyHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('embassy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='countries.embassy')),
            ],
        ),
    ]
